
# For download of raw images to local filesystem

# For download of raw images to local filesystem
[download]
source = "\\\\klient.uib.no\\FELLES\\LAB-IT\\IFT\\resfys\\FluidFlower\\FF2 25-26 masterdata fra 101\\Subset_20min_4h\\Experiment_3_subset_20min_4h"

[download.data.time.calibration]
times = [
    "00:15:00",
    "02:00:00",
    "04:00:00",
    "06:00:00",
    "20:00:00",
    "40:00:00",
    "60:00:00",
    "100:00:00",
    "200:00:00",
    "300:00:00",
    "400:00:00",
]

#[download.data.path.baseline]
#paths = ["DSC22892.JPG", "DSC22888.JPG", "DSC22887.JPG"]

[video]

[video.source]
folder = "fingers/tips/storage"                # relative to [data.results] when not absolute
extensions = [".png"]
recursive = false

[video.output]
formats = ["mp4"]
fps = 2.0
codec = "mp4v"
quality = 95
# resolution = [1280, 720] # optional [width, height]

[video.overlay]
show_elapsed_time = true
elapsed_time_format = "Elapsed: {:.2f} h"
show_note = true
note = "Experiment #3 - Segmentation"
font_scale = 2.5
thickness = 2
text_color = [255, 255, 255]
position = [20, 20]
box_enabled = true
box_color = [0, 0, 0]
box_alpha = 0.4
box_padding = 10
